drop table if exists board CASCADE;
create table board
(
 id bigint generated by default as identity,
 title varchar(255) not null,
 content varchar(1000) not null,
 writer varchar(20) not null,
 regDate TIMESTAMP not null,
 primary key (id)
);
